[project]
name = "mcp-unix-manual"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.3.0",
]
[project.scripts]
mcp-unix-manual = "unix_manual_server:main"
